setting:
  seed: 20000812
  os_environ:
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: 12315
    WORLD_SIZE: 4
    NODE_RANK: 0

  out_path: output/ProteinGym/esm2_t30_150M_UR50D.tsv
  dataset_dir: /cto_labs/AIDD/DATA/SaProt/ProteinGym/substitutions

model:
  model_py_path: esm/esm_mutation_model
  kwargs:
    config_path: /cto_labs/AIDD/WEIGHTS/Protein/esm2_t30_150M_UR50D
    load_pretrained: True

dataset:
  dataset_py_path: mutation_zeroshot_dataset
  dataloader_kwargs:
    batch_size: 256
    num_workers: 8
  kwargs: {}

Trainer:
  log_every_n_steps: 1
  devices: 4
  accelerator: gpu
  num_nodes: 1
  strategy:
    find_unused_parameters: False
  logger: False