setting:
  seed: 20000812
  os_environ:
    WANDB_API_KEY: ~
    WANDB_RUN_ID: ~
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: localhost
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0
  tensorboard:
    log_dir: tmp/MetalIonBinding
    name: esm2_8M

model:
#    Which model to use
  model_py_path: esm_mamba/esm_mamba_classification_model
  kwargs:
#    Arguments to initialize the specific class
    config_path: config/model/esm_mamba_8M.yaml
    load_pretrained: false
    num_labels: 2
    extra_config:
      pretrained_ckpt: results/Pretrain/esmm_8M_632K.pt

#    Arguments to initialize the basic class AbstractModel
  lr_scheduler_kwargs:
    last_epoch: -1
    init_lr: 1.0e-4
#    Weather to use this scheduler or not
    on_use: false

  optimizer_kwargs:
    betas: [0.9, 0.98]
    weight_decay: 0.01

  save_path: ~


dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: esm/esm_classification_dataset
  dataloader_kwargs:
    batch_size: 8
    num_workers: 8

  train_lmdb: /cto_labs/AIDD/DATA/SaProt/MetalIonBinding/AF2/normal/train
  valid_lmdb: /cto_labs/AIDD/DATA/SaProt/MetalIonBinding/AF2/normal/valid
  test_lmdb: /cto_labs/AIDD/DATA/SaProt/MetalIonBinding/AF2/normal/test
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: /cto_labs/AIDD/WEIGHTS/Protein/esm2_t6_8M_UR50D


#  Arguments to initialize Pytorch Lightning Trainer
Trainer:
  max_epochs: 200
  log_every_n_steps: 1
  strategy:
    find_unused_parameters: True
  logger: False
  enable_checkpointing: false
  val_check_interval: 0.5
  accelerator: gpu
  devices: 8
  num_nodes: 1
  accumulate_grad_batches: 1
  precision: 16
  num_sanity_val_steps: 0