dataset:
#    Arguments to initialize the basic class LMDBDataset
  dataset_py_path: esm/esm_ppi_dataset
  dataloader_kwargs: # deprecated, initalized through training args
    batch_size: 8
    num_workers: 8

  train_lmdb: /cto_labs/AIDD/DATA/SaProt/HumanPPI/normal/train
  valid_lmdb: /cto_labs/AIDD/DATA/SaProt/HumanPPI/normal/valid
  test_lmdb: /cto_labs/AIDD/DATA/SaProt/HumanPPI/normal/test
#    Arguments to initialize the specific class
  kwargs:
    tokenizer: /cto_labs/AIDD/WEIGHTS/Protein/esm2_t6_8M_UR50D
    max_length: 1024
    plddt_threshold: null